### ISSUE TITLE
Image cropping no longer works

### ISSUE THREAD

**Issue by chrisvanpatten** [alfreddatakillen/wpro#27]
Although there's code in wpro to hook into image cropping, it doesn't seem to work. While it's able to download the image for cropping, the cropped images don't seem to be able to make it back up to S3.

**Comment by alfreddatakillen** [comment]
Interesting. I have it working at some customers' servers. It would be nice with some more info on it!

**Comment by alfreddatakillen** [comment]
Sorry pushed the "close" button by mistake. :)

**Comment by chrisvanpatten** [comment]
No worries @alfreddatakillen but actually I noticed that it's working!

The only thing I did notice was that the new image doesn't replace the old image in the media browser popup, but it still does seem to work with the new code!

**Comment by chrisvanpatten** [comment]
(Also that seems to be the default behaviour in WordPress, so I don't think it's WPRO's fault)

**Comment by chrisvanpatten** [comment]
Since this works now, and I've confirmed that the other problem is a problem in WP core, I'm going to close this up :)
