### ISSUE TITLE
Error when activating plugin on Wordpress 4.1

### ISSUE THREAD

**Issue by mrodrigues** [alfreddatakillen/wpro#29]
Hi! I'm trying to activate the wpro plugin on a Wordpress 4.1 instance hosted in the OpenShift platform, but I get the following error message:

> Parse error: syntax error, unexpected '[' in /var/lib/openshift/54c886fee0b8cd4850000038/app-root/runtime/repo/wp-content/plugins/wpro/src/tmpdir.php on line 8 Fatal error: Call to a member function log() on a non-object in /var/lib/openshift/54c886fee0b8cd4850000038/app-root/runtime/repo/wp-content/plugins/wpro/wpro.php on line 67

My application has write permissions on the /tmp file. Did I do something wrong? Is this plugin incompatible with the latest Wordpress version?

**Comment by alfreddatakillen** [comment]
Hello! This is because your PHP version is before PHP 5.4. However, I believe it is a simple fix. Line 8 of tmpdir can be changed to: `public $cleanUpDirs = array();` 
I'll fix this error and deploy a new version in just a few minutes... Thanks for your report!

**Comment by alfreddatakillen** [comment]
Now fixed in [this commit](https://github.com/alfreddatakillen/wpro/commit/f8c6685016c8ec6e7b1c97dc58e2b933e94f297b).

**Comment by mrodrigues** [comment]
Thank you very much! :smile:
