### ISSUE TITLE
Current version eliminates WPRO_FOLDER option

### ISSUE THREAD

**Issue by chrisvanpatten** [alfreddatakillen/wpro#32]
I was using the WPRO_FOLDER option to allow me to use a single S3 bucket (and thus a single origin pull CDN endpoint) for multiple sites in a WordPress multisite install. The current iteration of the WPRO plugin in the master branch does away with this option.

**Comment by alfreddatakillen** [comment]
Just merged a pull request that fixes this for S3. (However, the support is supposed to be more generic and be moved out from the s3 class before the next release.)

**Comment by chrisvanpatten** [comment]
Amazing, thanks @alfreddatakillen! I'm really loving the increased flexibility... just gotta get all the missing features in there and it'll be perfect :)
